name: Post Code on PR Update

on:
  pull_request:
    branches:
      - main
      - master
    types: [synchronize]

jobs:
  post-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Post code to webhook
        run: |
          curl -X POST -H "Content-Type: application/json" -d @${{ github.workspace }} "https://webhook.botpress.cloud/a93d018d-71d5-45e9-8e01-caf7bc651b95"
